name: lint-build-test
on:
  push:
  pull_request:
    types: [closed, opened, edited]
    branches:
      - "*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install
        run: yarn install --frozen-lockfile
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test:ci
      - name: Build
        run: yarn build
